version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3.13-management"
    ports:
      - "5672:5672"  # AMQP port for the application
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  main-app:
    build: .
    command: "npm start"
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://user:password@rabbitmq
      # Add other necessary environment variables from .env file
    depends_on:
      rabbitmq:
        condition: service_healthy

  recognition-worker:
    build: .
    # The command specifically starts the worker script
    command: "node services/recognition-worker.js"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://user:password@rabbitmq
      # Add other necessary environment variables from .env file
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 3 # Start with 3 replicas to demonstrate scaling